name: Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    name: EsLint
    needs: conform
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    name: Test
    needs: conform
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Test
        run: npm run test

  build:
    needs: 
      - lint
      - test
    runs-on: ubuntu-latest
    name: Build Angular Project

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.0
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: weather-fe
          path: dist/